import type { Metadata } from 'next';
import './globals.css';
import { Header } from './_components/header';
import { CardModalProvider } from '@/components/providers/modal-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CardModalProvider />
        <Header />
        {children}
      </body>
    </html>
  );
}
